# build and test on linux, windows, mac with node 12,14
name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pnpmstore:
    env:
      CI: true
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 12, 14 ]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2

      - name: set env.pnpm_store_path
        run: echo "pnpm_store_path=${{github.workspace}}${{ matrix.os == 'windows'  && '\' || '/' }}.pnpm-store" >> $GITHUB_ENV
        shell: bash
      - name: install pnpm
        run: npm i -g pnpm@5
      - name: set pnpm store-dir
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: pnpm-store
        uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: pnpm-store-fallback
        if: steps.pnpm-store.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        id: pnpm-store-fallback
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-fallback-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-fallback-

      - name: install
        # if: steps.pnpm-store.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline --ignore-scripts
      - name: check store
        run: pnpm store status

  lint:
    needs: pnpmstore
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2
      - name: set env.pnpm_store_path
        run: echo "pnpm_store_path=${{github.workspace}}${{ matrix.os == 'windows'  && '\' || '/' }}.pnpm-store" >> $GITHUB_ENV
        shell: bash
      - name: pnpm-store
        uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install pnpm
        run: npm i -g pnpm@5
      - name: set pnpm store-dir
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: install
        run: pnpm install --frozen-lockfile --offline --ignore-scripts
      - name: install esbuild
        run: node node_modules/esbuild/install.js
      - name: build
        run: pnpm run build:ci
      - name: lint
        run: pnpm lint

  audit:
    needs: pnpmstore
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2
      - name: set env.pnpm_store_path
        run: echo "pnpm_store_path=${{github.workspace}}${{ matrix.os == 'windows'  && '\' || '/' }}.pnpm-store" >> $GITHUB_ENV
        shell: bash
      - name: pnpm-store
        uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install pnpm
        run: npm i -g pnpm@5
      - name: set pnpm store-dir
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: install
        run: pnpm install --frozen-lockfile --offline --ignore-scripts
      - name: audit
        run: pnpm audit

  test:
    needs: pnpmstore
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 12, 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2
      - name: set env.pnpm_store_path
        run: echo "pnpm_store_path=${{github.workspace}}${{ matrix.os == 'windows'  && '\' || '/' }}.pnpm-store" >> $GITHUB_ENV
        shell: bash
      - name: pnpm-store
        uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: install pnpm
        run: npm i -g pnpm@5
      - name: set pnpm store-dir
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: install-offline
        run: pnpm install --frozen-lockfile --offline --ignore-scripts
      - name: install esbuild
        run: node node_modules/esbuild/install.js
      - name: build
        run: pnpm run build:ci
      - name: run tests
        run: pnpm test:ci

      - name: archive tests temp directory
        if: failure()
        shell: bash
        run: tar -cvf test-temp.tar  --exclude="node_modules" --exclude=".yarn" --exclude="dist" --exclude=".pnp.js" temp/
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-failure-${{github.run_id}}-${{ matrix.os }}-${{ matrix.node }}
          path: |
            test-temp.tar
            temp/serve/jest-results.json
            temp/serve/junit.xml
            temp/build/jest-results.json
            temp/build/junit.xml
            pnpm-debug.log
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: test-success-${{github.run_id}}-${{ matrix.os }}-${{ matrix.node }}
          path: |
            temp/serve/jest-results.json
            temp/serve/junit.xml
            temp/build/jest-results.json
            temp/build/junit.xml

  build:
    needs: pnpmstore
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: checkout
        uses: actions/checkout@v2
      - name: set env.pnpm_store_path
        run: echo "pnpm_store_path=${{github.workspace}}${{ matrix.os == 'windows'  && '\' || '/' }}.pnpm-store" >> $GITHUB_ENV
        shell: bash
      - name: pnpm-store
        uses: actions/cache@v2
        id: pnpm-store
        with:
          path: ${{ env.pnpm_store_path }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: install pnpm
        run: npm i -g pnpm@5
      - name: set pnpm store-dir
        run: pnpm config set store-dir ${{ env.pnpm_store_path }}
      - name: install
        run: pnpm install --frozen-lockfile --offline --ignore-scripts
      - name: install esbuild
        run: node node_modules/esbuild/install.js
      - name: build
        run: pnpm run build
